# -*- coding: utf-8 -*-
"""Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-MzqJNviGoi1gnkrxOlNUIJp8lPzzQzr
"""

import pandas as pd
import numpy as np
df = pd.read_csv('/Users/Documents/SKCM_6March/Final_overall_data/final_matrix_filter_with_gene_name.csv')
df

# Rename the column
df.rename(columns={'common': 'Gene'}, inplace=True)

df

"""# Transpose"""

# Assuming 'df' is your Pandas DataFrame
transposed_df = df.transpose()

transposed_df

# Set the first row as column names and transpose the DataFrame
transposed_df.columns = transposed_df.iloc[0]

transposed_df

transposed_df= transposed_df.iloc[1:]

transposed_df

"""# Find number of zeroes and remove them (50%)"""

## count number of zeroes per gene ##
count = (transposed_df == 0).sum()
count

# count.to_csv('/Users/raghava_lab/Documents/SKCM_6March/Preprocessed_files/Zeroes_with_gene.csv', index=None)

m = 473/2
m

##find how many zeroes are less than half number of genes#
(count <= m)

############### remove less than 50% zeroes value genes ####################
a =[]
for i in transposed_df.columns:
    if ((transposed_df[i] == 0).sum() < m):
        a.append(transposed_df[i])

############ convert a into dataframe and than transpose file #########
df1 = pd.DataFrame(a).T
df1

df1.to_csv('/Users/raghava_lab/Documents/SKCM_6March/Preprocessed_files/After_Zeroes_Removal.csv')

"""# Variane Threshold ( remove features with a variance threshold below 25%)"""

from sklearn.feature_selection import VarianceThreshold
selector = VarianceThreshold(threshold = 0.25)
selector.fit(df1)
feature_indices = selector.get_support(indices = True)
df2 = df1.iloc[:, feature_indices]
df2

df2.to_csv('/Users/raghava_lab/Documents/SKCM_6March/Preprocessed_files/low_variance_features_removal.csv', index=None)

